### ISSUE TITLE
无法使用empm命令

### ISSUE THREAD

**Issue by paopaozhi** [paopaozhi/empm#11]
## 命令行日志

```shell
Traceback (most recent call last):
  File "D:\userapp\miniconda3\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\userapp\miniconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\userapp\miniconda3\Scripts\empm.exe\__main__.py", line 4, in <module>
    from empm.main import run
  File "D:\userapp\miniconda3\lib\site-packages\empm\main.py", line 9, in <module>
    from web.main import web_app
  File "D:\userapp\miniconda3\lib\site-packages\web\main.py", line 26, in <module>
    web_app.mount("/assets", StaticFiles(directory="web/html/dist/assets"), name="assets")
  File "D:\userapp\miniconda3\lib\site-packages\starlette\staticfiles.py", line 59, in __init__
    raise RuntimeError(f"Directory '{directory}' does not exist")
RuntimeError: Directory 'web/html/dist/assets' does not `exist`
```

**Comment by paopaozhi** [comment]
ci自动打包时，没有将web命令所需要的静态资源打包到pypi包中

**Comment by paopaozhi** [comment]
预计在下一个版本中修复该问题
